[tool.poetry]
name = "csv-bisect-gui"
version = "0.1.0"
description = ""
authors = ["insolor <insolor@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
bidict = "^0.23.1"
tkinter-layout-helpers = "^0.3.0"
alternative-encodings = {version = "^0.1.0", source = "dfint"}

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
pytest-cov = "^4.1.0"
hypothesis = "^6.98.15"
black = "^24.1.1"
isort = "^5.13.2"
ruff = "^0.3.0"
refurb = "^1.28.0"
flake8 = "^7.0.0"

[[tool.poetry.source]]
name = "dfint"
url = "https://dfint.github.io/pypi-index/"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.poe.tasks]
run = "python -m csv_bisect_gui.app"

[tool.poetry.scripts]
app = "csv_bisect_gui.app:main"
