[tool.poetry]
name = "csv-bisect-gui"
version = "0.1.0"
description = ""
authors = ["insolor <insolor@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
bidict = "^0.22.1"
tkinter-layout-helpers = "^0.3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
hypothesis = "^6.88.1"
black = "^23.10.1"
isort = "^5.12.0"
ruff = "^0.1.4"
refurb = "^1.22.1"
flake8 = "^6.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.poetry.scripts]
csv_bisect = "csv_bisect_gui.app:main"

[tool.poe.tasks]
run.script = "csv_bisect_gui.app:main"
